spring.application.name=MultipleServicesMapping

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.root=INFO
server.port=8080

email.service.url=http://localhost:8081/alert/DBEmail
