services:

  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"

  gateway:
    build: ./Gate
    container_name: gateway
    ports:
      - "80:80"
    depends_on:
      - eureka

  cool:
    build: ./cool
    container_name: cool
    ports:
      - "8094:8094"
    depends_on:
      - eureka

  fire:
    build: ./fire
    container_name: fire
    ports:
      - "8093:8093"
    depends_on:
      - eureka

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1